services:
  - type: web
    name: diabetes-backend
    env: python
    buildCommand: pip install -r project/backend/diabetes/requirements.txt
    startCommand: gunicorn diabetes.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: diabetes.settings
      - key: DATABASE_URL
        fromDatabase:
          name: diabetes-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    plan: free
    autoDeploy: true

databases:
  - name: diabetes-db
    plan: free
