# Generated by Django 5.2.4 on 2025-07-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('diabetic', models.IntegerField()),
                ('family_history', models.IntegerField()),
                ('medication_for_sugar', models.IntegerField()),
                ('sugary_food_intake', models.IntegerField()),
                ('physical_activity', models.IntegerField()),
                ('prediction', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
